name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e50af28040a872098034e70c6bb30eb505300865142d8bc58bd2c5fd289fa52"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
