name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bbb15ec6c81174a445dab6026cb3e8f11bf1ceee1d588960adbc3c76db668c5"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
