name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32ebd32779b938b756bad4e2cf21b6c0a84042fba9c33e58dbbf3fdea2aa5bc0"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
