name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b9edbe42ebe5cc0a4f43f4f10ed38652731f70241d524e185b9381014bd15f5"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
