name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad033dcdf0fbe7dd6725fa1bbb53096ee781f1ca5592738c06370c7e8143c3b"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
