name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc6ff15acfb1cb6671150dd74db998f856daef01acc9b7005f001b469aa9187a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
