name = "Catgirl Village's Modpack"
author = "Cynthia <cynthia@cynthia.dev>"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa733db857120d06d8952cb6969d6fe597c99a1c16c60720445031c9ecaa601"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
